datastore-support #20: add support to ecosystem scripts for managing datastore java ingestion service

diff --git a/bin/datastore-java-build b/bin/datastore-java-build
--- a/bin/datastore-java-build
+++ b/bin/datastore-java-build
@@ -4,7 +4,8 @@ source ~/datastore/datastore-support/env/datastore-env
 
 MVN_BIN=~/datastore/datastore-deployment/bin/mvn
 GRPC_DIR=~/datastore/datastore-java/datastore-grpc
-APP_DIR=~/datastore/datastore-java/datastore-service
+INGEST_APP_DIR=~/datastore/datastore-java/datastore
+QUERY_APP_DIR=~/datastore/datastore-java/datastore-service
 MVN_CMD="$MVN_BIN install"
 
 # check java home
@@ -15,6 +16,8 @@ test -z $M2_HOME && { echo "M2_HOME variable is not set"; exit 1; }
 
 # check for link to maven
 test -f $MVN_BIN || { echo "$MVN_BIN not found"; exit 1; }
+
+
 
 # change to datastore-grpc directory
 cd $GRPC_DIR || { echo "$GRPC_DIR not found"; exit 1; }
@@ -28,15 +31,30 @@ echo
 # run maven install
 eval "$MVN_CMD" || { echo "mvn install failed for $GRPC_DIR"; exit 1; }
 
-# change to datastore-service directory
-cd $APP_DIR || { echo "$APP_DIR not found"; exit 1; }
+
+
+# change to datastore directory
+cd $INGEST_APP_DIR || { echo "$INGEST_APP_DIR not found"; exit 1; }
 
 echo
 echo "============================================================================================================"
-echo "running $MVN_CMD in $APP_DIR"
+echo "running $MVN_CMD in $INGEST_APP_DIR"
 echo "============================================================================================================"
 echo
 
 # run maven install
-eval "$MVN_CMD" || { echo "mvn install failed for $APP_DIR"; exit 1; }
+eval "$MVN_CMD" || { echo "mvn install failed for $INGEST_APP_DIR"; exit 1; }
 
+
+
+# change to datastore-service directory
+cd $QUERY_APP_DIR || { echo "$QUERY_APP_DIR not found"; exit 1; }
+
+echo
+echo "============================================================================================================"
+echo "running $MVN_CMD in $QUERY_APP_DIR"
+echo "============================================================================================================"
+echo
+
+# run maven install
+eval "$MVN_CMD" || { echo "mvn install failed for $QUERY_APP_DIR"; exit 1; }
