datastore-support #17: add more console output to scripts used by ecosystem stop/start

diff --git a/bin/datastore-query-svc-stop b/bin/datastore-query-svc-stop
--- a/bin/datastore-query-svc-stop
+++ b/bin/datastore-query-svc-stop
@@ -8,7 +8,10 @@ if [ ! -f "$LOCKFILE" ]; then
 fi
 
 # stop datastore-service using pid in ~/datastore/datastore-deployment/var/lock/datastore-service.pid
-kill $(cat "$LOCKFILE")
+PID=`cat "$LOCKFILE"`
+echo "killing process id: $PID"
+kill $PID || { echo "failed to kill process id: $PID"; exit 1; }
 
-rm "$LOCKFILE"
+echo "removing lock file: $LOCKFILE"
+rm "$LOCKFILE" || { echo "failed to remove: $LOCKFILE"; exit 1; }
 
